(fn PlaceSelected ()
  (bind pc (Game|GetPlayerController 0))
  (if (and (> (Variables|Default|GetSelectedBuildType) 0) (>= (Variables|Default|GetCash) 2500.0))
    (bind (hit didHit) (Game|Player|GetHitResultUnderCursorbyChannel :self pc :TraceChannel "TraceTypeQuery1" :bTraceComplex false))
    (if didHit
      (bind (blocking initial time distance loc impact normal impactNormal physMat hitActor hitComponent hitBone bone item element face traceStart traceEnd)
        (Collision|BreakHitResult :Hit hit))
      (bind snapped (Math|Vector|VectorSnappedtoGrid :InVect impact :InGridSize 250.0))
      (bind buildLoc (+ snapped (Math|Vector|MakeVector :X 0.0 :Y 0.0 :Z 35.0)))
      (if (== (Variables|Default|GetSelectedBuildType) 1)
        (Game|SpawnActorfromClass :Class "/Game/Core/BuildablesV2/BP_RFBuildable_InnV2.BP_RFBuildable_InnV2_C" :SpawnTransform (Math|Transform|MakeTransform :Location buildLoc) :CollisionHandlingOverride "AlwaysSpawn")
        (CallFunction|ApplyBuildEconomy)
        (Development|PrintString "BUILT: GRAND INN // HOME + RESPAWN SERVICES" true true "(R=0.160000,G=0.950000,B=0.760000,A=1.000000)" 5.0)
        (elif (== (Variables|Default|GetSelectedBuildType) 2)
          (Game|SpawnActorfromClass :Class "/Game/Core/BuildablesV2/BP_RFBuildable_SmithyV2.BP_RFBuildable_SmithyV2_C" :SpawnTransform (Math|Transform|MakeTransform :Location buildLoc) :CollisionHandlingOverride "AlwaysSpawn")
          (CallFunction|ApplyBuildEconomy)
          (Development|PrintString "BUILT: BLACKSMITH // WEAPON ECONOMY ONLINE" true true "(R=1.000000,G=0.550000,B=0.150000,A=1.000000)" 5.0)
          (elif (== (Variables|Default|GetSelectedBuildType) 3)
            (Game|SpawnActorfromClass :Class "/Game/Core/BuildablesV2/BP_RFBuildable_UplinkV2.BP_RFBuildable_UplinkV2_C" :SpawnTransform (Math|Transform|MakeTransform :Location buildLoc) :CollisionHandlingOverride "AlwaysSpawn")
            (CallFunction|ApplyBuildEconomy)
            (Development|PrintString "BUILT: ARCANE UPLINK // CAPACITY +2,000" true true "(R=0.100000,G=0.720000,B=1.000000,A=1.000000)" 5.0)
            (elif (== (Variables|Default|GetSelectedBuildType) 4)
              (Game|SpawnActorfromClass :Class "/Game/Core/BuildablesV2/BP_RFBuildable_GuildHallV2.BP_RFBuildable_GuildHallV2_C" :SpawnTransform (Math|Transform|MakeTransform :Location buildLoc) :CollisionHandlingOverride "AlwaysSpawn")
              (CallFunction|ApplyBuildEconomy)
              (Development|PrintString "BUILT: GUILD HALL // PARTIES + QUESTS ONLINE" true true "(R=0.240000,G=0.620000,B=1.000000,A=1.000000)" 5.0)
              (elif (== (Variables|Default|GetSelectedBuildType) 5)
                (Game|SpawnActorfromClass :Class "/Game/Core/BuildablesV2/BP_RFBuildable_DungeonGateV2.BP_RFBuildable_DungeonGateV2_C" :SpawnTransform (Math|Transform|MakeTransform :Location buildLoc) :CollisionHandlingOverride "AlwaysSpawn")
                (CallFunction|ApplyBuildEconomy)
                (Development|PrintString "BUILT: DUNGEON GATE // INSTANCING + BOSS LOOT" true true "(R=0.720000,G=0.180000,B=1.000000,A=1.000000)" 5.0)
                (elif (== (Variables|Default|GetSelectedBuildType) 6)
                  (Game|SpawnActorfromClass :Class "/Game/Core/BuildablesV2/BP_RFBuildable_TravelDockV2.BP_RFBuildable_TravelDockV2_C" :SpawnTransform (Math|Transform|MakeTransform :Location buildLoc) :CollisionHandlingOverride "AlwaysSpawn")
                  (CallFunction|ApplyBuildEconomy)
                  (Development|PrintString "BUILT: SKY DOCK // PAID ROUTES ONLINE" true true "(R=0.950000,G=0.690000,B=0.180000,A=1.000000)" 5.0)
                  (else
                    (Development|PrintString "SELECT A BUILD CARD WITH 1-6" true true "(R=1.000000,G=0.320000,B=0.180000,A=1.000000)" 3.0))))))))
    (else
      (Development|PrintString "BUILD LOCKED // SELECT 1-6 AND KEEP $2,500 CASH" true true "(R=1.000000,G=0.240000,B=0.120000,A=1.000000)" 4.0)))))
