(event EventBeginPlay
  (bind pc (Game|GetPlayerController 0))
  (bind hud (UserInterface|CreateWidget "/Game/UI/WBP_RFOperatorHUD.WBP_RFOperatorHUD_C" pc))
  (UserInterface|Viewport|AddToViewport hud 10)
  (Input|SetInputModeGameAndUI pc hud "DoNotLock" false)
  (Development|PrintString "REALMFOUNDRY // TOP-DOWN MMO TYCOON // WASD PAN // 1-6 SELECT // CLICK TO BUILD // R RELEASE" true true "(R=0.170000,G=0.950000,B=0.750000,A=1.000000)" 12.0))

(event Collision|EventActorBeginOverlap (OtherActor))

(event EventTick (DeltaSeconds)
  (bind pc (Game|GetPlayerController 0))
  (bind me self)
  (if (Game|Player|IsInputKeyDown pc "W")
    (Pawn|Input|AddMovementInput me (Math|Vector|MakeVector :X 0.707 :Y 0.707 :Z 0.0)))
  (if (Game|Player|IsInputKeyDown pc "S")
    (Pawn|Input|AddMovementInput me (Math|Vector|MakeVector :X 0.707 :Y 0.707 :Z 0.0) -1.0))
  (if (Game|Player|IsInputKeyDown pc "D")
    (Pawn|Input|AddMovementInput me (Math|Vector|MakeVector :X 0.707 :Y -0.707 :Z 0.0)))
  (if (Game|Player|IsInputKeyDown pc "A")
    (Pawn|Input|AddMovementInput me (Math|Vector|MakeVector :X 0.707 :Y -0.707 :Z 0.0) -1.0))
  (if (Game|Player|WasInputKeyJustPressed pc "One")
    (Variables|Default|SetSelectedBuildType 1))
  (if (Game|Player|WasInputKeyJustPressed pc "Two")
    (Variables|Default|SetSelectedBuildType 2))
  (if (Game|Player|WasInputKeyJustPressed pc "Three")
    (Variables|Default|SetSelectedBuildType 3))
  (if (Game|Player|WasInputKeyJustPressed pc "Four")
    (Variables|Default|SetSelectedBuildType 4))
  (if (Game|Player|WasInputKeyJustPressed pc "Five")
    (Variables|Default|SetSelectedBuildType 5))
  (if (Game|Player|WasInputKeyJustPressed pc "Six")
    (Variables|Default|SetSelectedBuildType 6))
  (if (Game|Player|WasInputKeyJustPressed pc "LeftMouseButton")
    (CallFunction|PlaceSelected))
  (if (Game|Player|WasInputKeyJustPressed pc "R")
    (CallFunction|PublishUpdate)))
